databases:
  - name: ShikshaSaarthi
    databaseName: railway
    user: postgres

services:
  - type: web
    name: ShikshaSaarthi
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn ShikshaSaarthi.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ShikshaSaarthi
          property: connectionStringpostgresql://postgres:3FCeaFaECB1FgGa1bb5-53524-5fb63-@roundhouse.proxy.rlwy.net:46801/railway
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: account_sid
        value: "AC8f1031d6e4be7354259b0c58dd1aeebb"
      - key: auth_token
        value: "b355e70abfb41353b388a65e0345cc90"
      - key: verify_sid
        value: "FF59H9G39KMTPHJXHE6H2WTC"
      - key: Twilio_phone_number
        value: "+18889047058"